export const FETCH_SEARCH_DATA_REQUEST = 'FETCH_SEARCH_DATA_REQUEST';
export const FETCH_SEARCH_DATA_SUCCESS = 'FETCH_SEARCH_DATA_SUCCESS';
export const FETCH_SEARCH_DATA_ERROR = 'FETCH_SEARCH_DATA_ERROR';